# @no-log
POST http://localhost:8080/api/v1/databases/connect
Content-Type: application/json

{
   "url": "localhost",
   "port" : 3306,
   "password": "password",
   "username": "root",
   "driver": "mariadb"
}
###
# @no-log
POST localhost:8080/api/v1/databases/query
Content-Type: application/json

{
  "connectInfo": {
    "url": "localhost",
    "port" : 3306,
    "password": "password",
    "username": "root",
    "driver": "mariadb"
  },
  "sql": "select * from paytree.server_metadata"
}